package realEstatistic.model;

public enum FACILITY_TYPE {
    PRIMARY_SCHOOL, SECONDARY_SCHOOL, JUNIOR_COLLEGE, MIXED_SCHOOL, MRT, HAWKER_CENTER, PARK, CLINIC, SUPERMARKET,
    PREMIUM_BUS, E_WASTE
}
